# Generated by Django 6.0.6 on 2026-07-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro')], default='EUR', max_length=3),
        ),
    ]
